name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  AZURE_CONTAINER_APP_NAME: headless-pm-app
  AZURE_RESOURCE_GROUP: headless-pm-rg
  AZURE_CONTAINER_ENV: headless-pm-env

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Update or create the container app
            az containerapp update \
              --name ${{ env.AZURE_CONTAINER_APP_NAME }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --image ghcr.io/madhhouselabs/headless-project-management:latest \
              --set-env-vars \
                "SERVER_HOST=0.0.0.0" \
                "SERVER_PORT=8080" \
                "DATABASE_DIR=/data/db" \
                "UPLOAD_DIR=/data/uploads" \
                "MCP_ENABLED=true" \
                "ADMIN_API_TOKEN=${{ secrets.ADMIN_API_TOKEN }}" \
                "AZURE_OPENAI_ENDPOINT=https://klhub-resource.openai.azure.com/" \
                "AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }}" \
                "AZURE_OPENAI_EMBEDDING_DEPLOYMENT=embeds" \
              2>/dev/null || \
            az containerapp create \
              --name ${{ env.AZURE_CONTAINER_APP_NAME }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --environment ${{ env.AZURE_CONTAINER_ENV }} \
              --image ghcr.io/madhhouselabs/headless-project-management:latest \
              --target-port 8080 \
              --ingress external \
              --cpu 0.5 \
              --memory 1.0Gi \
              --min-replicas 1 \
              --max-replicas 3 \
              --env-vars \
                "SERVER_HOST=0.0.0.0" \
                "SERVER_PORT=8080" \
                "DATABASE_DIR=/data/db" \
                "UPLOAD_DIR=/data/uploads" \
                "MCP_ENABLED=true" \
                "ADMIN_API_TOKEN=${{ secrets.ADMIN_API_TOKEN }}" \
                "AZURE_OPENAI_ENDPOINT=https://klhub-resource.openai.azure.com/" \
                "AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }}" \
                "AZURE_OPENAI_EMBEDDING_DEPLOYMENT=embeds"

            # Get the app URL
            echo "Application URL:"
            az containerapp show \
              --name ${{ env.AZURE_CONTAINER_APP_NAME }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --query "properties.configuration.ingress.fqdn" \
              -o tsv | sed 's/^/https:\/\//'