name: Deploy to Azure

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    branches:
      - master

env:
  AZURE_CONTAINER_APP_NAME: headless-pm-app
  AZURE_RESOURCE_GROUP: headless-pm-rg
  AZURE_CONTAINER_ENV: headless-pm-env

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Update or create the container app
            az containerapp update \
              --name ${{ env.AZURE_CONTAINER_APP_NAME }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --image ghcr.io/madhouselabs/headless-project-management:latest \
              --set-env-vars \
                "SERVER_HOST=0.0.0.0" \
                "SERVER_PORT=8080" \
                "DATABASE_DIR=/data/db" \
                "UPLOAD_DIR=/data/uploads" \
                "MCP_ENABLED=true" \
                "ADMIN_API_TOKEN=${{ secrets.ADMIN_API_TOKEN }}" \
                "AZURE_OPENAI_ENDPOINT=https://klhub-resource.openai.azure.com/" \
                "AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }}" \
                "AZURE_OPENAI_EMBEDDING_DEPLOYMENT=embeds" \
              2>/dev/null || \
            az containerapp create \
              --name ${{ env.AZURE_CONTAINER_APP_NAME }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --environment ${{ env.AZURE_CONTAINER_ENV }} \
              --image ghcr.io/madhouselabs/headless-project-management:latest \
              --target-port 8080 \
              --ingress external \
              --cpu 0.5 \
              --memory 1.0Gi \
              --min-replicas 1 \
              --max-replicas 3 \
              --env-vars \
                "SERVER_HOST=0.0.0.0" \
                "SERVER_PORT=8080" \
                "DATABASE_DIR=/data/db" \
                "UPLOAD_DIR=/data/uploads" \
                "MCP_ENABLED=true" \
                "ADMIN_API_TOKEN=${{ secrets.ADMIN_API_TOKEN }}" \
                "AZURE_OPENAI_ENDPOINT=https://klhub-resource.openai.azure.com/" \
                "AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }}" \
                "AZURE_OPENAI_EMBEDDING_DEPLOYMENT=embeds"

            # Get the app URL
            echo "Application URL:"
            az containerapp show \
              --name ${{ env.AZURE_CONTAINER_APP_NAME }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --query "properties.configuration.ingress.fqdn" \
              -o tsv | sed 's/^/https:\/\//'